[pytest]
addopts = -v --tb=short --html=report.html --self-contained-html
testpaths = test_safa.py
markers =
    smoke: быстрые тесты для проверки что всё живо
    api: тесты API
    auth: тесты авторизации
