name: CI Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t qa-portfolio .

      - name: Start container
        run: |
          docker run -d -p 5000:5000 --name qa-api \
            --network host \
            -e DATABASE_URL=postgresql://admin:password@localhost:5432/testdb \
            qa-portfolio
          sleep 8

      - name: Check health endpoint
        run: curl http://localhost:5000/health

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pytest requests pytest-html
      - name: Install dependencies
        run: pip install pytest requests pytest-html pydantic

      - name: Run pytest
        run: python -m pytest test_safa.py -v -m smoke

      - name: Show logs if failed
        if: failure()
        run: docker logs qa-api