name: CI Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t qa-portfolio .

      - name: Start container
        run: |
          docker run -d -p 5000:5000 --name qa-api qa-portfolio
          sleep 5

      - name: Check health endpoint
        run: curl http://localhost:5000/health

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pytest requests pytest-html

      - name: Run pytest
        run: python -m pytest test_safa.py -v -m smoke

      - name: Show logs if failed
        if: failure()
        run: docker logs qa-api